---
- name: Deploy web App
  hosts: n2
  become: yes

  tasks:
  - name: install git
    yum:
      name: git
      state: present

  - name: Host code
    git:
      repo: https://github.com/ChibuzoNE/ansible-class-work.git
      dest: /var/www/html
...

